export const MOBILE_APP_RESUME_EVENT = 'codex-mobile-resume'
export const MOBILE_APP_PAUSE_EVENT = 'codex-mobile-pause'
export const MOBILE_NETWORK_ONLINE_EVENT = 'codex-mobile-online'
export const MOBILE_NETWORK_OFFLINE_EVENT = 'codex-mobile-offline'
export const MOBILE_BACK_BUTTON_EVENT = 'codex-mobile-back-button'
